### ISSUE TITLE
Question: Any possibilty to downscale on holidays ?

### ISSUE THREAD

**Issue by jchomat** [hjacobs/kube-downscaler#107]
Hello,

First, thanks for this tool very usefull for savings costs for cloud users.

if I want to go further, is there a possibility of downscale on specific days such as holidays ?

Thanks a lot,
BR,
Jérémy

**Comment by hjacobs** [comment]
@jchomat yes, you can add a `downtime` with absolute time ranges. See https://github.com/zalando-incubator/kubernetes-on-aws/pull/3149/commits/8fcef92fe061cc1c3be94fd288ef612328233c60 as an example for Easter 2020.

You can also add multiple holidays by using multiple absolute time ranges separated by comma.

**Comment by jchomat** [comment]
Nice, i wasn't sure to able to do it!
Thanks a lot!
