### ISSUE TITLE
downscaler/force-uptime: "false" is not working when defined in a namespace resource

### ISSUE THREAD

**Issue by johanra** [hjacobs/kube-downscaler#109]
When configuring  downscaler/force-uptime as "false" in a namespace resource , the uptime is still enforced.

apiVersion: v1
kind: Namespace
metadata:
  name: ns1
  annotations:
    downscaler/uptime: "Mon-Fri 07:30-19:30 CET"
    downscaler/force-uptime: "false"

I would expect this configuration to downscale outside the given uptime interval

**Comment by hjacobs** [comment]
You are right, that's a bug as the value is not checked: https://github.com/hjacobs/kube-downscaler/blob/master/kube_downscaler/scaler.py#L378
