### ISSUE TITLE
kube-system resources downscaling behavior is potentially problematic

### ISSUE THREAD

**Issue by erewok** [hjacobs/kube-downscaler#122]
We started using this project in our dev cluster and were surprised that our `coredns` pods in the `kube-system` namespace were downscaled, which means everything breaks. 

The documentation states:

> the deployment's namespace is not part of the exclusion list (kube-system is excluded by default)

After browsing the code, I was somewhat surprised to find this:

```python
    parser.add_argument(
        "--exclude-namespaces",
        help="Exclude namespaces from downscaling, comma-separated list of regex patterns (default: kube-system)",
        default=os.getenv("EXCLUDE_NAMESPACES", "kube-system"),
    )
```

I could be off-base here, but our deployment includes a configmap with `EXCLUDE_NAMESPACES` that didn't include `"kube-system"` (because of our reading of the docs above that it was included...), so we were surprised that kube-system was not protected _in addition_ to anything included in there. 

As a result, I would suggest making it difficult for users to accidentally downscale anything in `"kube-system"`. 

To do so, I'd probably add "kube-system" to anything the user has included in `"EXCLUDE_NAMESPACES"` or passed as an argument. In addition, I'd make another argument that is explicit about _removing_ this kube-system exclusion, something like `"--downscale-kube-system"`). 

This is all based on the assumption that downscaling things inside `"kube-system"` is pretty dangerous and should only be enabled on "expert mode".

Others may not agree, though, so I wanted to raise it here for discussion.

Thanks.

**Comment by hjacobs** [comment]
Thanks for creating this issue. I don't really want to treat `kube-system` in a special way other than having it excluded by default. Rationale: there are usually (in "real-life" setups) more infrastructure components which can be deployed in other custom namespaces (e.g. "infra", "monitoring", etc), so hard-coding `kube-system` will only solve this for an unknown fraction of users.

**Comment by erewok** [comment]
I had that thought as well and thought that may be the response. In that case, I'd probably try to make the documentation more explicit here.
