### ISSUE TITLE
Waiting to build with regex applied to main.py

### ISSUE THREAD

**Issue by jamessantos10** [hjacobs/kube-downscaler#17]
Good afternoon, yesterday I created the PR to adjust the regex -> https://github.com/hjacobs/kube-downscaler/pull/16, I am waiting for the build of the new image with this change applied. Could you do this build, and upgrade to dockerhub?

**Comment by hjacobs** [comment]
Sure :smile:

**Comment by hjacobs** [comment]
Here you go: https://github.com/hjacobs/kube-downscaler/releases/tag/0.5.1
