### ISSUE TITLE
Feature request: Annotation on Namespace

### ISSUE THREAD

**Issue by DaspawnW** [hjacobs/kube-downscaler#18]
Hi,

We have created for our developers an ephemeral instance concept. If a Demand or Service Manager wants to test a new feature we can deploy an ephemeral instance of our architecture incl some microservices or all. There you can also specify if this environment should be deleted after a time or should be available unlimited.

For the unlimited instances I'm searching for a feature to scale down this environment.
The complete ephemeral instance will be deployed in one namespace so it would be great to have an annotation on our namespace to define that all deployments or statefulsets are downscaled during non business hours.

I think if I look into the source code it seems you are only supporting statefulsets and deployments but not all statefulsets and deployments in a namespace.

What do you think?

Best regards,
 Björn

**Comment by hjacobs** [comment]
I think this is a valid feature request (makes sense to support this use case), would you be willing to provide a PR?

**Comment by hjacobs** [comment]
This was fixed in #30 and was just now released: https://github.com/hjacobs/kube-downscaler/releases/tag/0.8
