### ISSUE TITLE
Feature request: Amount of replicas to downscale to

### ISSUE THREAD

**Issue by grebois** [hjacobs/kube-downscaler#22]
Would be nice if instead of going to 0 replicas always, it could be parameterized and be set to 1 or 2, for big clusters it make sense not to kill all pods to keep the service running.

**Comment by hjacobs** [comment]
SGTM, will to do a PR? (also check #20 before doing so)

**Comment by grebois** [comment]
@hjacobs definitely, just don't have time this weeks, but if you can leave this open for a bit I will submit one, probably after #20 is already merged, so no problem.

**Comment by hjacobs** [comment]
@grebois do you have any opinion on the annotation name (see #38)?

**Comment by grebois** [comment]
merged
