### ISSUE TITLE
Is it possible to have multiple kinds (as deployment and statefulset for instance)?

### ISSUE THREAD

**Issue by axcosta** [hjacobs/kube-downscaler#27]
Trying to configure multiple kinds at the args but couldn't find the way. Is it feasible? Thanks!

**Comment by hjacobs** [comment]
Yes, that's possible with multiple `--kind` options, see https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/kube-downscaler/deployment.yaml#L25

I think this is inconsistent to the `--exclude-..` options, so maybe we fix it in the future.

**Comment by axcosta** [comment]
I've done that, but it seems that it only gets the last --kind argument. Look at the info log: "INFO: Downscaler started with config: Namespace(debug=False, default_downtime='never', default_uptime='always', dry_run=False, exclude_deployments='kube-downscaler,downscaler', exclude_namespaces='kube-system', exclude_statefulsets='', grace_period=900, interval=60, kind=['statefulset'], namespace=None, once=False)".

**Comment by hjacobs** [comment]
This was now fixed with v0.7+: https://github.com/hjacobs/kube-downscaler/releases
