### ISSUE TITLE
Default original replicas flag

### ISSUE THREAD

**Issue by AndresPineros** [hjacobs/kube-downscaler#41]
First, thanks for the project, it has helped us a lot.

It would be nice to be able specify a "--default-original-replicas" flag. This way if a new pod is added and someone forgets to add the "original-replicas" annotation, it will be recreated anyways.

**Comment by hjacobs** [comment]
I don't understand your use case, can you elaborate what you want to achieve?

**Comment by AndresPineros** [comment]
I use the --default-uptime in my clusters because we have around 150 deployments and we don't want to manage the uptime tag for all of them individually.

The problem with this is that all the deployments from our namespaces get downscaled, and they aren't upscaled if they don't have the "original-replicas" tag.

If one of our devs forgets to add the "original-replicas" tag, the service will remain downscaled until our alarm systems alert or a customers complains. So, it would be nice to also have a "--default-original-replicas". We would set this value to 1 so that when the uptime starts all the services are initiated with at least one replica. This way we ensure no outages because someone forgot an annotation.

**Comment by AndresPineros** [comment]
Just realized the "original-replicas" is set automatically, which makes this issue nonsense. Sorry.
