### ISSUE TITLE
Scale back up if `exclude` annotation is added while downscaled

### ISSUE THREAD

**Issue by jasongwartz** [hjacobs/kube-downscaler#43]
Sometimes, after our cluster has downscaled for the evening, a developer would like to scale something back up temporarily to test. At the moment, this would involve adding the `exclude` annotation, then manually triggering a scale-up with `kubectl scale`, then removing the exclude annotation to scale back down.

It would be great if the downscaler automatically recognized when something has an `original-replicas` annotation but is also marked as `exclude`, or in a namespace which is excluded, and scales those back up to their original replicas.

(I may be able to attempt a PR for this sometime soon, but not right away)

**Comment by hjacobs** [comment]
SGTM
