### ISSUE TITLE
Feature request: different logic

### ISSUE THREAD

**Issue by dh-harald** [hjacobs/kube-downscaler#47]
As I mentioned earlier, I'd like to use a different scenario. I need to downscale the replica, not no upscale later, so I'm suggesting a different logic, which maybe can live the existing logic as well...
I suggest two additional parameter:
`upscale_period` and `downscale_period`. You can set a period of time (for example in my case) only for downtime.
```
upscale_period: never
downscale_period: "Mon-Fri 19:00-19:10 UTC"
```
This means, that if a resource up between 19:00 and 19:10 it will downscale it.
(that will be a same logic for the upscale as well)
Pros:
- you can do my task (no upscale, just downscale)
- you don't need to take care about excluding on later period (for example if the developers needs the deployment temporary)

Could you implement this (or any other method), that I can downscale only my deployment)
Thanks

**Comment by hjacobs** [comment]
This is now released in [v0.13](https://github.com/hjacobs/kube-downscaler/releases/tag/0.13).
