### ISSUE TITLE
Downscale deployment with HPA not working

### ISSUE THREAD

**Issue by caiohaz** [hjacobs/kube-downscaler#49]
I have a deployment that has a HorizontalPodAutoScaler, in this scenario the kube-downscaler change replicas to 0 but HPA change again to original value, it's generate a "looop" and de deployment never is downscaled.

I need add/change some config to this works?

**Comment by caiohaz** [comment]
Someone?

**Comment by hjacobs** [comment]
What metrics do you use for HPA?

**Comment by caiohaz** [comment]
@hjacobs targetCPUUtilizationPercentage and targetMemoryUtilizationPercentage,i found this project that scaling hpa: https://github.com/k8s-restdev/scheduled-scaler for you refference.

**Comment by darjisanket** [comment]
We dont have crd support. Do we have any other option similar downsize deployments with HPA.

**Comment by caiohaz** [comment]
Ok, thank you!
