### ISSUE TITLE
Downscaler --kind appends to default value (deployment)

### ISSUE THREAD

**Issue by AndresPineros** [hjacobs/kube-downscaler#55]
I think the downscaler has this bug:
https://bugs.python.org/issue16399

If I set the kind as:
```
- --kind=statefulset
```

I get this in the logs:
```
2019-06-03 06:09:53,137 INFO: Downscaler v0.15 started with debug=True, default_downtime=never, default_uptime=<redacted>, downscale_period=never, downtime_replicas=0, dry_run=False, 
exclude_deployments=kube-downscaler,downscaler, exclude_namespaces=<redacted>, exclude_statefulsets=, grace_period=900, interval=60, kind=['dep
loyment', 'statefulset'], namespace=None, once=False, upscale_period=never
```
It appends statefulset to deployment instead of overriding deployment with statefulset.
Maybe use a different strategy for this variable? Instead of multiple flags, receive a string and convert it to an array?

**Comment by hjacobs** [comment]
I guess the same approach (comma separated list of resource types) as in [kube-janitor](https://github.com/hjacobs/kube-janitor) makes sense.

**Comment by AndresPineros** [comment]
As a quick fix I just removed the default "deployment" value. Would you consider this an acceptable solution? Anyways, compatibility will be broken for arguments like
```
--kind=deployment
--kind=statefulset
```
For the case above, I think it is better to get a clear "this field is required" error than a weird behavior that only downscales statefulsets, which is going to take people more time to figure out after an upgrade.

**Comment by hjacobs** [comment]
@AndresPineros are you willing to do a PR with the same behavior as `kube-janitor` has (option `--include-resources` comma separated list of plural resource names)?

> Resource collections should be all lowercase and plural, whereas kinds are CamelCase and singular.

from https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md

So I think also the naming was wrong (kind is singular, e.g. "StatefulSet") and plural makes more sense here (as the downscaler works on collections of resources).

**Comment by hjacobs** [comment]
Released in https://github.com/hjacobs/kube-downscaler/releases/tag/0.16
