### ISSUE TITLE
downscaler and preemptible nodes

### ISSUE THREAD

**Issue by materemias** [hjacobs/kube-downscaler#56]
With GKE preemptible nodes every node gets restarted at least once in 24h. 
If I set up downscaler like
```
  tag: 0.15
  args: 
     - --default-uptime=Mon-Fri 07:00-19:00 Europe/Berlin
     - --downtime-replicas=1
```
it scales down at the end of the day, remembers original replicas but when the downscaler pod restarts (with it's node) it gets somehow forgotten. resulting in everything stuck on 1 replicas even when uptime comes.

I could reproduce this by simply restarting downscaler with a different uptime setting (forcing it to upscale) after a downscale happened and experienced the same behaviour.

Do you have any idea how to get it work?

**Comment by hjacobs** [comment]
Sounds similar to #44 which should have been fixed in v0.15. :thinking:

**Comment by materemias** [comment]
after the downscaler pod restarts it reports
![image](https://user-images.githubusercontent.com/529994/58800846-43183b80-8609-11e9-861e-4f96e96c829a.png)
in logs, maybe it has something to do with it.
Is there anything I could check to provide better insights?

**Comment by hjacobs** [comment]
@materemias do you still have this problem?

**Comment by materemias** [comment]
@hjacobs I can confirm it is resolved now!
