### ISSUE TITLE
helm chart defaults to an old release

### ISSUE THREAD

**Issue by nirdothan** [hjacobs/kube-downscaler#57]
https://github.com/hjacobs/kube-downscaler/blob/78007f0cb14147136ffc129d9a1f88fb5d10f585/helm-chart/values.yaml#L26

**Comment by hjacobs** [comment]
True, thanks for noticing. Please note that I'm not using Helm myself, that's why the Helm Chart might not be 100% supported.

**Comment by hjacobs** [comment]
Updated it manually now, but this should be automated.

**Comment by nirdothan** [comment]
Thanks

**Comment by hjacobs** [comment]
I'm no longer supporting the Helm chart in this repo, see #108.
