### ISSUE TITLE
Downscale and upscale period annotation frome resources not taken in consideration

### ISSUE THREAD

**Issue by simplifia** [hjacobs/kube-downscaler#67]
if no value for period is defined on namespace level or before, annotation on deployment is not take in consideration. The following statement is never satisfied:

` elif upscale_period != 'never' or downscale_period != 'never':` 

quick fix: 

     def autoscale_resource(resource: pykube.objects.NamespacedAPIObject, upscale_period: str,       downscale_period: str,
                       default_uptime: str, default_downtime: str, forced_uptime: bool, dry_run: bool,
                       now: datetime.datetime, grace_period: int, downtime_replicas: int,    namespace_excluded=False):

    try:
        exclude = namespace_excluded or ignore_resource(resource)
        original_replicas = resource.annotations.get(ORIGINAL_REPLICAS_ANNOTATION)
        downtime_replicas = int(resource.annotations.get(DOWNTIME_REPLICAS_ANNOTATION, downtime_replicas))

        if exclude and not original_replicas:
            logger.debug('%s %s/%s was excluded', resource.kind, resource.namespace, resource.name)
        else:
            replicas = resource.replicas
            ignore = False
            upscale_period = resource.annotations.get(UPSCALE_PERIOD_ANNOTATION, upscale_period)
            downscale_period = resource.annotations.get(DOWNSCALE_PERIOD_ANNOTATION, downscale_period)
            if forced_uptime or (exclude and original_replicas):
                uptime = "forced"
                downtime = "ignored"
                is_uptime = True
            elif upscale_period != 'never' or downscale_period != 'never':
                uptime = upscale_period
                downtime = downscale_period
                if helper.matches_time_spec(now, upscale_period) and helper.matches_time_spec(now, downscale_period):
                    logger.debug('Upscale and downscale periods overlap, do nothing')
                    ignore = True
                elif helper.matches_time_spec(now, upscale_period):
                    is_uptime = True
                elif helper.matches_time_spec(now, downscale_period):
                    is_uptime = False
                else:
                    ignore = True
            else:
                uptime = resource.annotations.get(UPTIME_ANNOTATION, default_uptime)
                downtime = resource.annotations.get(DOWNTIME_ANNOTATION, default_downtime)
                is_uptime = helper.matches_time_spec(now, uptime) and not helper.matches_time_spec(now, downtime)

            update_needed = False

            if not ignore and is_uptime and replicas == downtime_replicas and original_replicas and int(original_replicas) > 0:
                logger.info('Scaling up %s %s/%s from %s to %s replicas (uptime: %s, downtime: %s)',
                            resource.kind, resource.namespace, resource.name, replicas, original_replicas,
                            uptime, downtime)
                resource.replicas = int(original_replicas)
                resource.annotations[ORIGINAL_REPLICAS_ANNOTATION] = None
                update_needed = True
            elif not ignore and not is_uptime and replicas > 0 and replicas > int(downtime_replicas):
                target_replicas = int(resource.annotations.get(DOWNTIME_REPLICAS_ANNOTATION, downtime_replicas))
                if within_grace_period(resource, grace_period, now):
                    logger.info('%s %s/%s within grace period (%ds), not scaling down (yet)',
                                resource.kind, resource.namespace, resource.name, grace_period)
                else:

                    logger.info('Scaling down %s %s/%s from %s to %s replicas (uptime: %s, downtime: %s)',
                                resource.kind, resource.namespace, resource.name, replicas, target_replicas,
                                uptime, downtime)
                    resource.annotations[ORIGINAL_REPLICAS_ANNOTATION] = str(replicas)
                    resource.replicas = target_replicas
                    update_needed = True
            if update_needed:
                if dry_run:
                    logger.info('**DRY-RUN**: would update %s %s/%s', resource.kind, resource.namespace, resource.name)
                else:
                    resource.update()
    except Exception as e:
        logger.exception('Failed to process %s %s/%s : %s', resource.kind, resource.namespace, resource.name, str(e))

**Comment by hjacobs** [comment]
I haven't checked this yet, but can you create a PR with a test to reproduce the problem?

**Comment by mikehalmaho** [comment]
I'm quite keen for this fix so please can you have a look at this: https://github.com/hjacobs/kube-downscaler/pull/70

**Comment by hjacobs** [comment]
Released: https://github.com/hjacobs/kube-downscaler/releases/tag/19.9.0
