### ISSUE TITLE
specify absolute scaling schedules

### ISSUE THREAD

**Issue by kevingessner** [hjacobs/kube-downscaler#71]
In addition to the supported weekday+time scaling schedules, kube-downscaler should support absolute time ranges for uptime and downtime periods.  I imagine these would be specified as either a range of numeric unix timestamps or a string format like ISO-8601.

For example, `downscaler/uptime: "2019-10-03T14:00:00+00:00-2019-10-04T02:00:00+00:00"` would specify scaling for precisely that period from 2pm UTC October 3 to 2am UTC October 4.

**Comment by hjacobs** [comment]
Sounds OK, what is your use case (for context)?

**Comment by kevingessner** [comment]
Cool!  I work a PR next week.  We're using kube-downscaler to manage test environments, scaling them up on demand by editing the annotations, and having them automatically scale down a couple hours later.  It's easier to specify absolute timestamps (and avoids them 'magically' scaling up again a week later).

**Comment by hjacobs** [comment]
Released: https://github.com/hjacobs/kube-downscaler/releases/tag/19.10.0
