### ISSUE TITLE
Only downscale, with no automatic upscale

### ISSUE THREAD

**Issue by fardin01** [hjacobs/kube-downscaler#81]
I've read the docs and still can't judge what the correct configuration for my use case is (if it's supported at all).

What I need is to simply downscale the cluster every day at 17:00 and that's it. I don't need to bring it back up automatically. Is this use case supported?

**Comment by hjacobs** [comment]
@fardin01 yes, that's supported. There is also an example in the README: https://github.com/hjacobs/kube-downscaler#alternative-logic-based-on-periods (this will never upscale automatically)

**Comment by hjacobs** [comment]
@fardin01 I hope my answer was helpful. Closing.
