### ISSUE TITLE
Deployments scaled down even though downtime=never

### ISSUE THREAD

**Issue by elranr** [hjacobs/kube-downscaler#84]
`2020-01-27 14:33:05,882 INFO: Scaling down Deployment default/flask-v1-tutorial from 1 to 0 replicas (uptime: Sun-Fri 00:00-23:59 UTC, downtime: never)
`
When uptime cover most of the day , I did try some other variation but the deployments goes down every time .

**Comment by hjacobs** [comment]
@elranr I think your weekdays for uptime might lead to this situation --- the weekday "from" must be before "to" (Sunday is not before Friday as ISO weeks start with Monday). 

I added a check and test for this situation: https://github.com/hjacobs/kube-downscaler/commit/1972f6fe2b0ca8c8ab1d518e65185551ecadc635

**Comment by elranr** [comment]
Our work week starting from Sunday, ending on Friday... How can I change it?

**Comment by hjacobs** [comment]
@elranr I changed the logic to allow `Sun-Fri`, please check https://github.com/hjacobs/kube-downscaler/releases/tag/20.1.0

**Comment by elranr** [comment]
I did try to configure it again , viewing the logs , you can see :  

```
2020-01-28 12:30:35,279 INFO: Scaling down Deployment default/flask-v1-tutorial from 1 to 0 replicas (uptime: Sun-Fri 06:00-22:30 Asia/Jerusalem, downtime: never)
```

Should be up and not down (UTC = 12:30 at the log)

**Comment by hjacobs** [comment]
@elranr did you upgrade the kube-downscaler to 20.1.0?

**Comment by elranr** [comment]
Approved - Works on 20.1.0 as it should, thanks! , how I add a weekend schedule regardless the daily schedule?

**Comment by hjacobs** [comment]
@elranr what do you mean with "add a weekend schedule regardless the daily schedule"?
