### ISSUE TITLE
support grace period for updated deployments

### ISSUE THREAD

**Issue by runningman84** [hjacobs/kube-downscaler#87]
Right now the docs state that " i.e. updated deployments will immediately be scaled down regardless of the grace period."

It would be great if an updated deployment would mean that the it would be upscaled for a grace period. This would allow us to use it in our ci cd pipelines... Right now they fail once a developer commits something at night because the health check does not pass after a deployment...

**Comment by hjacobs** [comment]
I would consider adding a feature to read a "deployment time" annotation similar to https://github.com/hjacobs/kube-janitor/pull/55

**Comment by runningman84** [comment]
The janitor even deletes stuff. My usecase is slightly different I just want to be able to deploy at night even though my uptime is normally set to office hours only.

**Comment by usman396** [comment]
Is there any progress on this?
