### ISSUE TITLE
Error with helm chart if I use value namespace.active_in 

### ISSUE THREAD

**Issue by mercantiandrea** [hjacobs/kube-downscaler#90]
When use value namespace.active_in with helm chart the pod start with the namespaces between "namespace_name" and this presence of " is not managed in the code.

Install Helm chart
helm install kube-downscaler incubator/kube-downscaler --version 0.4.0 --namespace kube-system --values ../tmp/incubator_kube-downscaler/0.4.0/incubator-kube-downscaler-profile.yaml

Use this value file 

_**../tmp/incubator_kube-downscaler/0.4.0/incubator-kube-downscaler-profile.yaml**_
namespace:
  **active_in: dev**
replicaCount: 1
image:
  tag: 20.2.0
debug:
  enable: True

Check deployment

_**k get deploy -n kube-system kube-downscaler -o yaml**_
...
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kube-downscaler
        app.kubernetes.io/name: kube-downscaler
    spec:
      containers:
      - args:
        - --interval=60
        - --namespace=**"dev"**
        - --debug
        image: hjacobs/kube-downscaler:20.2.0
        imagePullPolicy: IfNotPresent
        name: kube-downscaler
        resources: {}
...

Error in logs: **/%22dev%22/**

_**k logs --follow -n kube-system kube-downscaler-68896fc54b-8f4vd**_
2020-03-20 14:11:40,145 DEBUG: Starting new HTTPS connection (1): 10.100.0.1
2020-03-20 14:11:40,153 DEBUG: https://10.100.0.1:443 "GET /api/v1/namespaces/%22dev%22/pods HTTP/1.1" 200 134
2020-03-20 14:11:40,159 DEBUG: https://10.100.0.1:443 "GET /apis/apps/v1/namespaces/**%22dev%22**/deployments HTTP/1.1" 200 159

If I edit the deployment 

_**k edit deploy -n kube-system kube-downscaler**_
... 
 template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kube-downscaler
        app.kubernetes.io/name: kube-downscaler
    spec:
      containers:
      - args:
        - --interval=60
        - --namespace=**dev**
        - --debug
        image: hjacobs/kube-downscaler:20.2.0
        imagePullPolicy: IfNotPresent
        name: kube-downscaler
        resources: {}
...

Now it works: **/apis/apps/v1/namespaces/dev/deployments HTTP/1.1" 200 None**

_**k logs --follow -n kube-system kube-downscaler-7c7bdd79bd-w7jfz**_
2020-03-20 14:17:38,029 DEBUG: Starting new HTTPS connection (1): 10.100.0.1
2020-03-20 14:17:38,044 DEBUG: https://10.100.0.1:443 "GET /api/v1/namespaces/dev/pods HTTP/1.1" 200 None
2020-03-20 14:17:38,052 DEBUG: https://10.100.0.1:443 "GET /apis/apps/v1/namespaces/**dev**/deployments HTTP/1.1" 200 None

**Comment by hjacobs** [comment]
I'm no longer officially supporting the Helm chart in this repo, see #108.
